### PR TITLE
Updated block confirmations map for Goerli network.

### LINKED ISSUE #1005: Block confirmations dict not updated
Block confirmations dict is not updated for Goerli network.

### PR DESCRIPTION
**Pull request by mariacarmina**
Fixes #1005  .

Changes proposed in this PR:

- updated block confirmations map for Goerli.

### CODE REVIEW

**Comment by calina-c** [comment]
@mariacarmina new configurations for networks will be done using a brownie config file. Right now, it is minimal and left to the user to configure, but if you want to help improve it, any help is appreciated.

**Comment by calina-c** [comment]
@trentmc should this still be done in main? The brownie version will automatically pick up on the `required_confs` key in the network-config file. Also, with the current config we have in main, the user can define any block confirmation number. So I assume this issue is only for the default in Example Config? Not sure what we're trying to do here.

@mariacarmina this seems to update the poll interval and not the config itself, is that the goal?

**Comment by trentmc** [comment]
> Not sure what we're trying to do here.

Me neither 

We should be focusing on getting Brownie branch as main branch 

It could be that this pr becomes fully obsolete

**Comment by mariacarmina** [comment]
I did the modifications before brownie was integrated and I noticed that some maps weren't updated for goerli. I thought this PR was closed since we are focusing on a different config.

**Comment by calina-c** [comment]
I'll leave this still open in case of emergency. For now, let's focus on the brownie branch.

**Pull request closed without merging**
