### PR TITLE
Deprecates deploy fake OCEAN.

### LINKED ISSUE #278: Deprecate creating fake OCEAN from within ocean.py
**Is your feature request related to a problem? Please describe.**

In ocean.py for marketplace README quickstart, we generate fake OCEAN as explicit step. Most recently for #200.

Alex mentioned late last week that now ocean contracts repo generates fake OCEAN, and then it shows up in barge. If this is truly the case then we don't need the explicit step in OCEAN.

**Describe the solution you'd like**
Deprecate creating fake OCEAN from within ocean.py

Make sure it works in the marketplace README.

**TODOs**

- [x] Revive Calina's PR
- [ ] test the PR, fix as needed
- [ ] commit PR to main
- [ ] new ocean_lib release to pypi
- [ ] test "import ocean_lib" in marketplace README, does it work?

~~Notes: fixing this will unblock #201 - SQL alchemy. PR #276~~ (That issue is deprecated, don't need)

### PR DESCRIPTION
**Pull request by calina-c**
Fixes #278.

Changes proposed in this PR:

- deprecate deploy_fake_ocean.

Do not review/merge yet, needs checking.

### CODE REVIEW

**Comment by calina-c** [comment]
Postponed.

**Comment by mariacarmina** [comment]
Reopened according to @trentmc comment on [https://app.zenhub.com/workspaces/ocean-main-5e5e5a97e91ce03f380fb9b7/issues/oceanprotocol/ocean.py/278](url)

**Comment by calina-c** [comment]
@mariacarmina @trentmc what is the status of this? Was there any work done except for the reopening? Should I re-assign this to myself?

**Comment by trentmc** [comment]
@calina-c , it's best if you sync with @mariacarmina

**Comment by mariacarmina** [comment]
> @mariacarmina @trentmc what is the status of this? Was there any work done except for the reopening? Should I re-assign this to myself?
I have just tested with `tox` to see if I received the same error regarding deploying fake OCEAN.

**Comment by calina-c** [comment]
superseded.

**Pull request closed without merging**
