### PR TITLE
Fixes placement of status flags.

### LINKED ISSUE #339: Asset status object
**Describe the bug**
Ocean.py should follow the new status object in the metadata (https://github.com/oceanprotocol/OEPs/tree/master/8/v0.5#status-attributes)
The status object is located in the metadata service, and not in root

Actual code:
https://github.com/oceanprotocol/ocean.py/pull/314/files#diff-4fe12d33e5b6cf223d037f7ebc710c73cca03d661a204ab6cf19a5a3951f084aR74

(This will require a provider update as well)

### PR DESCRIPTION
**Pull request by calina-c**
Work on #339 .

Changes proposed in this PR:

- moves "status" flags in metadata service, instead of root

### CODE REVIEW

**Review by mariacarmina — APPROVED** [review]

**Comment by trentmc** [comment]
The functionality for `isOrderDisabled` looks sane, from a 5-min review.

This github issue says it's about getting ocean.py to supporting all the `status` attributes listed in the OEP: `isListed`, `isRetired`, `isOrderDisabled`. But I only see support for `isOrderDisabled`. How are we handling the other two? (Or are we explicitly not handling them?)

**Review by trentmc — CHANGES_REQUESTED** [review]
See my previous comment

**Comment by calina-c** [comment]
> The functionality for `isOrderDisabled` looks sane, from a 5-min review.
> 
> This github issue says it's about getting ocean.py to supporting all the `status` attributes listed in the OEP: `isListed`, `isRetired`, `isOrderDisabled`. But I only see support for `isOrderDisabled`. How are we handling the other two? (Or are we explicitly not handling them?)

Not yet. The only implementation already done is for isOrderDisabled. The problem was the placement of it, which was in root instead of the metadata service. The rest of the flags are not covered yet.

**Comment by trentmc** [comment]
> Not yet. The only implementation already done is for isOrderDisabled. 

Thanks. Could you clarify in the issue then please? Because this PR says it implements the issue.

**Comment by calina-c** [comment]
> > Not yet. The only implementation already done is for isOrderDisabled.
> 
> Thanks. Could you clarify in the issue then please? Because this PR says it implements the issue.

I think that is what Alex meant in the issue. But I'll mark this PR as "work on ..." instead of "closes" and check with him when he's back. Is that ok?

**Review by trentmc — APPROVED** [review]

**Pull request merged**
