### PR TITLE
Fix #1340 - New splash image for ocean.py README + copyright year update

### LINKED ISSUE #1340: New splash image for ocean.py README
### Background / motivation

We'll be releasing new blog posts on ocean.py in coming weeks. The first six will go through the quickstart READMEs; then we will go on to more advanced topics. 

For these posts, we have new image content, in the form of pythons swimming 🐍 🌊. Each post gets its own. The best image will go in the [first post](https://blog.oceanprotocol.com/getting-started-with-ocean-py-part-1-introduction-installation-530295c3d3b4). The image is below.

Leading up to those posts being released, @calina-c has suggested to put the first/best image as the splash image for ocean.py. I think that's a great idea!

### TODO for this issue
- add the new image to to the top of README.md
- likely, remove the "Ocean" banner image in README.md (why: two images is overkill) 

### The image itself

(FYI there is another image proposal too. I'll update accordingly if needed.)

python-oceanpy

### PR DESCRIPTION
**Pull request by trentmc**
Fixes #1340

Notes: it looks good in both (a) Ubuntu Chrome desktop (b) ios chrome smartphone with image `width=300`, centered (as in the first commit to this PR).

### CODE REVIEW

**Comment by trentmc** [comment]
@calina-c please review. 

FYI Veronica plans to make videos starting tomorrow, so I want to get this in sooner rather than later.

FYI 2: I believe the failing CI / unit tests are unrelated to this change? If yes, let's merge (and fix those tests separately). If no, do you know what's up?

**Comment by calina-c** [comment]
@trentmc Sorry, I didn't realise you started this and I also added the splash image to https://github.com/oceanprotocol/art inside a `splashes folder`. I am good with both versions: uploaded here or there. But please let me know whether I should delete it from the art repo, if we keep it here.

**Comment by calina-c** [comment]
> FYI 2: I believe the failing CI / unit tests are unrelated to this change? If yes, let's merge (and fix those tests separately). If no, do you know what's up?

unrelated, I think the Provider in barge didn't start c2d. I'll rerun the tests and they should work

**Comment by trentmc** [comment]
Oh, I like the idea to put the image in the art repo.

Could you make the changes to this PR, please? I'm afk

**Review by mariacarmina — APPROVED** [review]

**Comment by trentmc** [comment]
We hope to publish the blog post 1 and Veronica's accompanying video soon. 

The video will show the README.md. Which depends on this PR being merged (and pypi release).

Re timing: Veronica was hoping for today (Thu), though I think given the timing of this PR, and some video edits needed, it's tomorrow (Fri) at soonest.

@calina-c what else do we need to merge this PR? The CI failures are unrelated to this issue.

**Pull request merged**
