### PR TITLE
add full graphql support

### LINKED ISSUE #911: Add graphql to supported data types
See https://github.com/oceanprotocol/pm/issues/176 for full EPIC
So far, we supported  'url ' and 'ipfs' types for data storage
Since https://github.com/oceanprotocol/provider/pull/537, there is a new one, called 'graphql'.
This allows publishers to publish datasets and use graphql querys as datasource.

Format for graphql type is as follows:
 - type: graphql
 - url :  server endpoint url
 - query: the actual query to be executed

Example:
```
[
        {
            "type": "graphql",
            "url": "http://172.15.0.15:8000/subgraphs/name/oceanprotocol/ocean-subgraph",
            "query": """
                    query{
                        nfts(orderBy: createdTimestamp,orderDirection:desc){
                            id
                            symbol
                            createdTimestamp
                        }
                    }
                    """,
        }
    ]
```

Sometimes, it's not enough to have one simple query, you need some input from user. This can be achieved with something like:
 - prepare asset with graphql storage
```
[
        {
            "type": "graphql",
            "url": "http://172.15.0.15:8000/subgraphs/name/oceanprotocol/ocean-subgraph",
            "query": """
                    query nfts($nftAddress: String){
                        nfts(where: {id:$nftAddress},orderBy: createdTimestamp,orderDirection:desc){
                            id
                            symbol
                            createdTimestamp
                        }
                    }
                    """,
        }
    ]
```
as you can see, there is a query parameter called nftAddress.
 - add consumerParameters to ddo.service as 
 ```
[
            {
                "name": "nftAddress",
                "type": "text",
                "label": "nftAddress",
                "required": True,
                "description": "Nft to search for",
            }
        ]
```

When downloading the dataset, user has to pass  userdata to provider request

### PR DESCRIPTION
**Pull request by alexcos20**
Closes #911 

Changes proposed in this PR:

- add simple graphql query support
- add parametrized graphql query support
- add integration tests

### CODE REVIEW

**Comment by trentmc** [comment]
This looks amazing. I'll approve once I see that the test results have passed.

**Comment by alexcos20** [comment]
This still requires custom version of provider in barge :)

**Comment by alexcos20** [comment]
some c2d flows are broken, also https://github.com/oceanprotocol/ocean.py/issues/905 seems to be an issue.

There are no tests broken in the files changed in this PR

**Comment by alexcos20** [comment]
Readme can be updated using [this test](https://github.com/oceanprotocol/ocean.py/blob/feature/graphql/tests/integration/test_graphql.py)

**Comment by trentmc** [comment]
> [Alex wrote] So, there is some work required on this PR

@alexcos20 is this ready for review now, in your view?

@calina-c have you had a look at it?

**Comment by calina-c** [comment]
> > [Alex wrote] So, there is some work required on this PR
> 
> @alexcos20 is this ready for review now, in your view?
> 
> @calina-c have you had a look at it?

@alexcos20 @trentmc I looked into this issue but the last comment is about creating or updating a readme. I asked Alex about it on Slack but it got sidetracked by other issues. Do I need to do anything else than review? Who needs to create the readme?

**Comment by trentmc** [comment]
> @alexcos20 @trentmc I looked into this issue but the last comment is about creating or updating a readme. I asked Alex about it on Slack but it got sidetracked by other issues. Do I need to do anything else than review? Who needs to create the readme?

Alex has already created a README, as part of this PR.
https://github.com/oceanprotocol/ocean.py/pull/912/files#diff-835809bbd034b6078d5c5d2b016ff5fc6ad0b8f95a96574e7f99f8effea3c1ea

**Review by calina-c — APPROVED** [review]

**Pull request merged**
