### PR TITLE
Remove magic method and transfer functions directly.

### PR DESCRIPTION
**Pull request by calina-c**
Helps #1165. Turns out both magically calling the functions and transferring them DOES keep their `__doc__`. However, only transfering them keeps them in the dir(class) function. This should now be compatible with autocompletions etc.

### CODE REVIEW

**Comment by trentmc** [comment]
I'm confused. How does this solve #1165? 

For example: if I'm a python developer using ocean.py, where do I go to learn about the interface for `Datatoken.transfer()?`

If the answer is "Go look at the solidity code" then it isn't solved.

If the answer is "It's in the docstring" but we don't expose the docstring anywhere, then it isn't solved.

**Comment by calina-c** [comment]
@trentmc 

I am attaching two screenshots of various ways the user can learn about the contract structure without looking at the abi directly. You can see the contract is a datatoken, but it can be any type of object instantiating ContractBase.

You can use `dir(contract)` to show its attributes, as well as `contract.__dict__`. From the list of attributes, you can select any function and get its interface. i.e. 

```
> contract.balanceOf
> <ContractCall 'balanceOf(address account)'>
```

As well as the docstring (taken from solidity)

```
> contract.balanceOf.__doc__
> '\n    A public view or pure contract method.\n\n    Attributes\n    ----------\n    abi : dict\n        Contract ABI specific to this method.\n    signature : str\n        Bytes4 method signature.\n    '
```

Screenshot 2023-01-10 at 15 00 29
Screenshot 2023-01-10 at 15 01 01

**Comment by trentmc** [comment]
> You can use dir(contract) to show its attributes, as well as contract.__dict__

Thanks. FYI I was aware of these even when writing the function.

Those are only of limited use. I sometimes use them during interactive debugging.

But they do not meet the goals of this issue, which is to have a great reference for what methods are available. E.g. 
```python
"""
  def balanceOf(address: str) -> int:
    Returns the balance of this address.
    :param: address of interest
    :return: balance, in wei 
"""
```

I don't see it as a huge effort to do this. It will be manual and tedious, but in the end probably only take a few days. 

And it will serve as a great jumping-off point for the follow-up issue of having great docs.

**Comment by calina-c** [comment]
- They weren't on the contract previously, so the interface should be much better now. I will keep this change if possible
- I'll also add the docstrings. I thought the purpose was for better debugging and autocomplete, but I can write these as well.

**Comment by trentmc** [comment]
> They weren't on the contract previously, so the interface should be much better now. I will keep this change if possible

Sounds good.

> I'll also add the docstrings. 

Sounds good.

> I thought the purpose was for better debugging and autocomplete, but I can write these as well.

Having both is complementary. Glad we're in sync:)

**Review by trentmc — APPROVED** [review]

**Comment by trentmc** [comment]
FYI I approved this PR. And changed the description from "solves X" to "helps X"

**Comment by calina-c** [comment]
I re-requested a review now with docstrings added :)

**Pull request merged**
