### PR TITLE
Integrate V4 smart contracts' functions

### LINKED ISSUE #488: Integrate all V4 Smart contracts interfaces to ocean.py

### LINKED ISSUE #550: Integrate V4 contracts' functions + implement ERC721 Factory unit tests
Integrate V4 contracts' functions + implement ERC721 Factory unit tests.

### PR DESCRIPTION
**Pull request by mariacarmina**
Fixes #550  .

Changes proposed in this PR:

- integrate v4 smart contracts' functions;
- add unit tests for `ERC721 Factory`.

### CODE REVIEW

**Comment by mariacarmina** [comment]
I will update the contracts version in `setup.py` for testing with `v4main` branch from contracts repo in the next commit.

**Comment by calina-c** [comment]
1. please do not create PRs to main, all PRs for v4 should be directed to the v4 branch
2. I am not sure this is what had to be done. I think the ticket refers to the "contracts interfaces" vaguely, and I believe it is about integrating the contracts themselves. Since we do not send calls to interfaces, I assume the Interfaces in contracts are only for internal contracts usage. So this ticket is about integrating "interfaces to the contracts" == ocean.py classes that correspond to the contracts repo. Not about integrating classes that correspond tot the interfaces in the contracts repo.

Can you advise, @alexcos20 or @trentmc? There is no description on this ticket, but I've always assumed we are discussing v4 contracts in this case. Please make sure to add proper descriptions when assigning tickets, especially since Maria wasn't at the meetings where we discussed the v4 tickets. CC @AnaLoznianu

**Comment by mariacarmina** [comment]
> 1. please do not create PRs to main, all PRs for v4 should be directed to the v4 branch
> 2. I am not sure this is what had to be done. I think the ticket refers to the "contracts interfaces" vaguely, and I believe it is about integrating the contracts themselves. Since we do not send calls to interfaces, I assume the Interfaces in contracts are only for internal contracts usage. So this ticket is about integrating "interfaces to the contracts" == ocean.py classes that correspond to the contracts repo. Not about integrating classes that correspond tot the interfaces in the contracts repo.
> 
> Can you advise, @alexcos20 or @trentmc? There is no description on this ticket, but I've always assumed we are discussing v4 contracts in this case. Please make sure to add proper descriptions when assigning tickets, especially since Maria wasn't at the meetings where we discussed the v4 tickets. CC @AnaLoznianu

It makes much more sense right now, thank you.

**Comment by calina-c** [comment]
@mariacarmina please update the v4main branch to be in sync with the current main, after the recent merge for organising (common ddo folder split-ups and unifying Asset and DDO classes into V3Asset)

Then kindly change the base for this PR to v4main.

**Review by calina-c — CHANGES_REQUESTED** [review]

**Comment by mariacarmina** [comment]
Screenshot from 2021-11-03 02-03-42

**Review by calina-c — APPROVED** [review]

**Pull request merged**
