### PR TITLE
Fix #1048 Improve CI for dependencies

### LINKED ISSUE #1048: Improve CI for dependencies
TODOs:

- [ ] add dependabot
- [ ] check that build & install deps on multiple OS works fine

### PR DESCRIPTION
**Pull request by alexcos20**
Fixes #1048

Changes proposed in this PR:

- add dependabot
- check that build & install deps on multiple OS works fine

### CODE REVIEW

**Comment by trentmc** [comment]
This is cool to see! Good idea!

Is there a github issue for this?

**Comment by alexcos20** [comment]
No, it just did it quickly while we were iterating on another pr :)

**Comment by trentmc** [comment]
> No, it just did it quickly while we were iterating on another pr :)

Thanks. To help tracking, I created a github issue, and linked to it here.

I will review for reals now

**Comment by alexcos20** [comment]
Ocean.py tests are failing in main, so that's why they are failing here as well

**Comment by trentmc** [comment]
I haven't worked with either of these things to be able to judge it well.

Perhaps have @calina-c review too?

But at the very least the tests need to pass. Looks like the issue of "py.test" is causing failure here too. How to proceed?

**Comment by alexcos20** [comment]
https://github.com/oceanprotocol/ocean.py/commits/main    - a lot of failed tests because people are still doing commits to main branch directly

let me fix the tests

**Comment by trentmc** [comment]
> let me fix the tests

nice!

**Review by trentmc — APPROVED** [review]
Let's ship this. Approved

**Comment by alexcos20** [comment]
We have a couple of tests failing, and not because of this PR.
Ocean.py has some issue, let's fix them in another PR

**Comment by trentmc** [comment]
> We have a couple of tests failing, and not because of this PR.
> Ocean.py has some issue, let's fix them in another PR

More than a couple, unfortunately. There are 5-10 github issues on related problems. Calina's work on brownie will fix several of these. And there is still some other work too. 

(Therefore if you're going to spend time to fix these, I recommend doing it in Calina's brownie branch)

**Pull request merged**
