### PR TITLE
add codacy coverage

### PR DESCRIPTION
**Pull request by alexcos20**
towards #146 
After merge to main, we can add the requirement to branch protection

### CODE REVIEW

**Comment by trentmc** [comment]
@alexcos20 thanks to your changes, codacy.com now has a coverage report available for `ocean.py` repo.

Which means we can put the coverage badge into the README. So I just did that, in commit https://github.com/oceanprotocol/ocean.py/pull/177/commits/f000486a3f5a8ad7a3457e8195594a58527d0030.

**Review by trentmc — CHANGES_REQUESTED** [review]
Makes sense so far. I ran the commands locally and it didn't complain either.

One remaining hitch: I cannot see the coverage results from the codacy.com dashboard. It says "Hey! Seems like we stopped receiving your coverage results. Check your CI server!". If that's resolvable here, let's resolve it. (Or maybe the fastest way is to merge then check?)

**Comment by alexcos20** [comment]
We need to merge to main first, after that codacy will pickup the coverage

**Comment by trentmc** [comment]
> We need to merge to main first, after that codacy will pickup the coverage

At codacy.com it gives the impression that you can set up testing for branches. At first glance it looked like I might have set it up in a minute or two, but after fiddling for a bit, it wasn't that easy. 

So therefore yeah let's merge to main first. I approve:)

**Review by trentmc — APPROVED** [review]

**Pull request merged**
