### PR TITLE
Issue 101- added new example

### LINKED ISSUE #101: Add compute-to-data example README: make it work
Goal of this issue: write down some super-basic flow for compute-to-data example, as a new file in ocean.py READMEs repo. Just "make it work". Rough & messy is ok!

Then, Trent will follow up with "make it good" in #279

-----

RESULT: @alexcos20 just shared to me (@trentmc) the following steps. This is enough of a starting point for me to work with. Therefore I will close this issue.

**STEPS:**
1. clone https://github.com/oceanprotocol/ocean.js-cli  , follow Readme how to install & run
2. run "npm run cli h"  to get a list of all commands
3. publish your python algo:  npm run cli publishAlgo metadata/pythonAlgo.json     , you will get a did (ex: did:op:BfABF938B0DA61B5A05C19eC14C21E0E32D70158)
4. publish your dataset :     npm run cli publish metadata/simpleDataset.json  - (ex: did:op:02d3EE10b8bc734e9306d999c12cE304d40869bb)
5. allow your algo for C2D for that dataset:       npm run cli allowAlgo did:op:02d3EE10b8bc734e9306d999c12cE304d40869bb did:op:BfABF938B0DA61B5A05C19eC14C21E0E32D70158
6. start a compute job:       npm run cli startCompute did:op:02d3EE10b8bc734e9306d999c12cE304d40869bb did:op:BfABF938B0DA61B5A05C19eC14C21E0E32D70158   (you will get a jobId   3a985f1f88af4fe08e26b4d0d857be57)
7. get compute job status:      npm run cli getCompute 3a985f1f88af4fe08e26b4d0d857be57
8. watch the logs & algo output above

### PR DESCRIPTION
**Pull request by Akif-G**
Fixes #101 .

Changes proposed in this PR:

- New example, tested working.
- Uses https for Aquarius and Provider
- Uses rinkeby.

### CODE REVIEW

**Comment by trentmc** [comment]
Note: we just had a call to get in sync on how to move forward.

What not to have: 
- don't have Rinkeby - just use barge, it's simpler
- don't use marketplace flow. Just have Alice transfer -> Bob. Avoids redundant code.

Here's what to have:
- starting point is [simple quickstart](https://github.com/oceanprotocol/ocean.py/blob/main/READMEs/datatokens-flow.md). Just copy-and-paste those three steps so that it's self-encapsulated.
- then change / expand on the last part ("Publish datatokens"):
  - Alice publishes a datatoken, and asset info (asset info from your PR)
  - Alice transfers datatoken to Bob (no market needed)
  - Bob consumes the data asset, including building some model from the csv

Doing this single README will cover off all of the epic, not just the first bullet. Epic: [ocean.py#8](https://app.zenhub.com/workspaces/ocean-main-5e5e5a97e91ce03f380fb9b7/issues/oceanprotocol/ocean.py/8).

**Comment by calina-c** [comment]
@Akif-G also, can you please check the conformity of markdown files and reformat them using the settings here? https://github.com/oceanprotocol/ocean-remark

**Comment by trentmc** [comment]
@Akif-G fyi, I converted this to draft given that it's still a WIP. 

When it's ready to review: click "update branch" button (and fix any conflicts), click "ready for review" button, then please ping me that you'd like a review. Thank you:)

**Comment by Akif-G** [comment]
new PR created

**Pull request closed without merging**
