### PR TITLE
Fix erc721 terminology in functions and variables

### LINKED ISSUE #700: Functions & variables renaming to conform to the nomenclature
As described here: https://github.com/oceanprotocol/ocean.py/pull/697#discussion_r79791971 we need some renaming  to align with our terminology :

- `create_nft_token() ` -->  `create_data_nft()`
- `erc721_token` -->  `erc721_nft`
- `nft_token` -->  `erc721_nft`

### PR DESCRIPTION
**Pull request by md0x**
Signed-off-by: Pablo Maldonado <pablo@oceanprotocol.com>

Fixes #700 .

Changes proposed in this PR:

- `create_nft_token()` --> ~~`create_data_nft()`~~ `create_erc721_nft()`
- `erc721_token `--> `erc721_nft`
- `nft_token `--> `erc721_nft`
- `erc721_token.py` --> `erc721_nft.py`
- `ERC721Token `--> `ERC721NFT`

### CODE REVIEW

**Comment by calina-c** [comment]
LGTM, please update with v4main after the DSP refactoring merge, you might have conflicts or places where the old namings were used.

**Comment by calina-c** [comment]
@md0x can you please fix the conflicts?

**Comment by trentmc** [comment]
I'm really happy to see this all.

```
0. create_nft_token() --> create_data_nft()
1. erc721_token --> erc721_nft
2. nft_token --> erc721_nft
3. erc721_token.py --> erc721_nft.py
4. ERC721Token --> ERC721NFT
```

I just realized: to make naming even more consistent, we could update (0) to:
```0. create_nft_token() --> create_erc721_nft()```

**Comment by md0x** [comment]
> I'm really happy to see this all.
> 
> ```
> 0. create_nft_token() --> create_data_nft()
> 1. erc721_token --> erc721_nft
> 2. nft_token --> erc721_nft
> 3. erc721_token.py --> erc721_nft.py
> 4. ERC721Token --> ERC721NFT
> ```
> 
> I just realized: to make naming even more consistent, we could update (0) to: `0. create_nft_token() --> create_erc721_nft()`

Thank you, change added

**Pull request merged**
