### PR TITLE
Update web3.py to v5.19.0

### LINKED ISSUE #77: Update to latest web3.py v5
The path for the web3 utils has changed from:

web3.py/web3/utils/ to web3.py/web3/_utils/

accordingly the following ocean_lib modules for Python 3 are broken:

/usr/local/lib/python3.8/dist-packages/ocean_lib/models/data_token.py
/usr/local/lib/python3.8/dist-packages/ocean_lib/web3_internal/contract_base.py
/usr/local/lib/python3.8/dist-packages/ocean_lib/web3_internal/web3_overrides/request.py
/usr/local/lib/python3.8/dist-packages/ocean_lib/models/bpool.py

### PR DESCRIPTION
**Pull request by mariacarmina**
Fixes #77 .

Changes proposed in this PR:

- update web3.py to the latest version;
- refactored a bit the code where needed to integrate the modifications;
- removed deprecated functions from the previous version.

### CODE REVIEW

**Comment by mariacarmina** [comment]
Still 13 failed unit tests... so it is still in progress

**Review by calina-c — COMMENTED** [review]
Fantastic work, Maria! I am impressed with the thoroughness and speed of this! Chapeau 👒

As discussed on Slack, I would like to have 2 more things included:
- [ ] check that marketplace README still works fine under the new changes, or if it needs to be adjusted in any way
- [ ] run a check of all camelCase occurrences inside the code. Now that web3.py is correct in using snake_case, we should not have any other camelCase variables and functions.

**Comment by mariacarmina** [comment]
Note: I have tested the marketplace-flow README and I found some warnings related to some deprecated functions from the previous version, but in rest it's working fine. I will create a separate ticket for this issue.

**Comment by mariacarmina** [comment]
> Fantastic work, Maria! I am impressed with the thoroughness and speed of this! Chapeau womans_hat
> 
> As discussed on Slack, I would like to have 2 more things included:
> 
>     * [x]  check that marketplace README still works fine under the new changes, or if it needs to be adjusted in any way
> 
>     * [ ]  run a check of all camelCase occurrences inside the code. Now that web3.py is correct in using snake_case, we should not have any other camelCase variables and functions.

Regarding the last checkbox, I am not so sure about that, because there are many occurrences to replace and some of them provide from contract function calls which are written in js. Maybe we can ask for other opinions, too. @DMats or @trentmc

**Comment by trentmc** [comment]
Re camelcase: if the python method is meant to be the 1:1 match of an underlying solidity method, then the name should remain the same. Really really helps for debuggability. This means if the solidity method is camelcase then the python method should be too.

Also re camelcase: if any changes are done, they are best done in a separate issue. It would be a straight up "refactoring" issue. So even if there are a lot of changes, it will have low cognitive overhead to verify. But if you mix a refactoring commit with other changes in the commit, it blows up the complexity.

**Comment by mariacarmina** [comment]
> Re camelcase: if the python method is meant to be the 1:1 match of an underlying solidity method, then the name should remain the same. Really really helps for debuggability. This means if the solidity method is camelcase then the python method should be too.
> 
> Also re camelcase: if any changes are done, they are best done in a separate issue. It would be a straight up "refactoring" issue. So even if there are a lot of changes, it will have low cognitive overhead to verify. But if you mix a refactoring commit with other changes in the commit, it blows up the complexity.

So do you agree to create a separate issue related to switching to snake_case wherever it's possible?

**Comment by trentmc** [comment]
Not wherever it's possible. There's a constraint as my first point states.

**Comment by mariacarmina** [comment]
> Not wherever it's possible. There's a constraint as my first point states.

Despite contract function calls, forgot to mention.

**Comment by trentmc** [comment]
Yes create a separate issue for camelcase.

**Review by calina-c — APPROVED** [review]

**Pull request merged**
