### PR TITLE
Update artifacts

### LINKED ISSUE #615: [v4] Update artifacts
https://github.com/oceanprotocol/contracts/pull/437 changed the `setMetaData` contract function signature.  It added a new `metaDataProof[]` argument. This issue is to update Ocean.py v4 to use the new artifacts.

### PR DESCRIPTION
**Pull request by DMats**
Closes #615.

Changes proposed in this PR:

- Update artifacts directory from ~/.ocean/ directory created by barge
  * Barge commit: 7e650bbd25a2627f475514c3701146b788da808b
  * Contracts branch: v4main_postaudit, commit: 26abee59da67f105166fca03aa8f16c1dcadc659
- Update `ERC721Template.setMetaData` to include `data_proofs` argument

TODO:

- [x] Update `ERC721Factory.startMultipleTokenOrder` (remove `amount`, add `v`, `r`, `s`, and `providerData`)
- [x] Update `ERC20Template.startOrder` (remove `amount`, add `v`, `r`, `s`, and `providerData`)
- [x] Update `ERC20TemplateEnterprise.startOrder` (remove `amount`, add `v`, `r`, `s`, and `providerData`)
- [x] not needed ~~Update `ERC20Template.ProviderFees` event (add `providerData`, `v`, `r`, `s`)~~
- [x] not needed ~~Update `ERC2TemplateEnterprise.ProviderFees` event (add `v`, `r`, `s`, and `providerData`)~~
- [x] Add `ERC20Template.getPermissions`
- [x] Add `ERC20TemplateEnterprise.getPermissions`
- [x] not needed ~~Add `ERC20Roles.getPermissions`~~
- [x] not needed ~~Add `ERC721Template.MetadataValidated` event~~

### CODE REVIEW

**Review by mariacarmina — COMMENTED** [review]
I think publish flow needs to be updated as well, because it uses set_metadata function.

**Comment by DMats** [comment]
> I think publish flow needs to be updated as well, because it uses set_metadata function.

@mariacarmina Thanks for reviewing!  You're right that `test_publish_flow` uses `asset.create` which in turn calls `set_metadata` which I've already updated with the new `data_proofs` argument.

**Review by calina-c — APPROVED** [review]

**Comment by calina-c** [comment]
I accidentally approved. @DMats can you please make sure to copy the artifacts from barge, instead of ocean-contracts? It's much safer this way.

**Comment by DMats** [comment]
Sure I can do that.  Thanks for reviewing!

**Review by calina-c — APPROVED** [review]

**Pull request merged**
